### ISSUE TITLE
Anybody succeeded in installing the mwi application on WIndows server with MySQL?

### ISSUE THREAD

**Issue by kulsw** [Myopengrid/mwi#10]
Dear Colleagues,

I have an issues regarding the installation of mwi on Windows Server 2008. At the step 2, I cannot see any error message or key to proceed to step 3. Debug application indicates, "http://(my ip address)/install/ajax/confirm_database 404 (Not Found)." I need help!!!

**Comment by JeffCost** [comment]
I don't have experience with windows servers, but I believe you are having problems with the "clean urls". With apache we have .htaccess file that rewrites the url without the index.php. You can force mwi to use the index.php in de urls and see if this help with your issue. To do that edit the file application/config/application.php and change:

``` php
'url' => '',
```

to

``` php
'url' => 'http://yourdomain-or-ip', // no trailing slash
```

and

``` php
'index' => '',
```

to

``` php
'index' => 'index.php',
```

It is just a guess, like I said I don't have experience with windows servers.

**Comment by kulsw** [comment]
Dear JeffCost,

I really appreciate for your comment. The initial parameter of index thing was "index => index.php" Thus, I didn't have to change it. If I put the URL information, it made 404 error. BTW, I am using IIS. If you have any comment or suggestion, please let me know more!

Thanks!!!

**Comment by JeffCost** [comment]
I am taking a look (weekend) on this issue and will get back to you as soon I have some results.

**Comment by kulsw** [comment]
Really appreciate it! Thank you!!!

**Comment by JeffCost** [comment]
I had to do some changes in the code for compatibility with IIS, but now it should work ok. I added in the public directory a  file called web.config.example. This file should take care of the "index.php" problems and url rewrites. Before start installation there is a couple of things you MUST do.
1 - Re download mwi
2 - Rename the file web.config.example to web.config. Create the application in your server (right click on the public folder and select "convert to application" and restart IIS.
3- Be sure to have full permissions on the following:
    FILES
    application/config/application.php
    application/config/database.php
    application/bundles.php

   DIRECTORIES
   storage
   bundles
   public/themes
   public/bundles

  There still a couple of issues when uploading modules and themes. You are not going to be able to upload zip files using the application backend (administration area). A workaround for that is to do it manually. Unzip a module inside the bundles directory and a theme inside public/themes directory. After that you should be able to activate/install/configure using the application backend.

Please let me know if this works for you.

**Comment by kulsw** [comment]
Dear JeffCost,

I cannot thank you enough. BTW, the IIS indicates that it cannot read the web.config file. If possible, could you check it for me? I am doing the best that I can do but. Please, help me.

**Comment by kulsw** [comment]
One more question about creating an appliation. What is the value of the application pool for public folder?

**Comment by JeffCost** [comment]
Sorry kulsw, I don't have much knowledge of IIS, but I will try to make a video tutorial showing how I got mwi to work with IIS. I will post the video link here when it is done.

**Comment by kulsw** [comment]
Dear Jefferson,

Thank you very much! I will do research on it by myself more! The video will be helpful to me! Thanks!!!

**Comment by JeffCost** [comment]
Hi Kulsw, I have a video tutorial up:

[https://www.youtube.com/watch?v=8XPJPc2RfEg](https://www.youtube.com/watch?v=8XPJPc2RfEg)

I will be closing this issue for now.
Thank you.
