### ISSUE TITLE
Error: menu.make.navigation

### ISSUE THREAD

**Issue by hack13** [Myopengrid/mwi#14]
I am getting error 500 over and over and over again: when i look at the logs this is what I get:

2013-09-11 23:19:43 ERROR - Pages event listener for [menu.make.navigation] got an empty link set.

**Comment by JeffCost** [comment]
Can you provide more details? it's a brand new installation?

**Comment by hack13** [comment]
It is a brand new installation running on Ubunt 12.04 LTS with the latest version of PHP 5.3 and MySQL
