### ISSUE TITLE
Cache needs to be cleared at the database level after upgrading?

### ISSUE THREAD

**Issue by GwynethLlewelyn** [Myopengrid/mwi#15]
Hiya,

I've upgraded MWI to the latest Git commit (since the last version stopped working). This worked quite well, even after figuring out a slight error on the documentation: where, at the end, it says "your_directory/bundles.php" it should say "your_directory/application/bundles.php".

All worked well until I uploaded the Grid Map module (which I believe hasn't been updated) or looked at the "welcome" splash screen. Here I get lots of missing images — so many missing images, in fact, that the Grid Map is empty. The missing images come mostly from wrong URLs. Note that I'm using Nginx, not Apache, so some errors might be due to that.

I wondered if this is happening because the cache isn't cleared, but the cache directory is empty. On the other hand, it's clear that some images on the splash screen are pointing to wrong URLs. This can be the way URLs are being parsed by the PHP framework — they might not always be Nginx-friendly.

You can take a look at http://opensim.betatechnologies.info/welcome to see what I'm talking about.

I'd like to know if there is a way to delete the cache at the database level (assuming that makes sense!) to start debugging this issue. Then, unfortunately, it means fixing Nginx rules, which might be the real culprit. This takes time and patience, so I'm trying to deal with the more obvious issues first!

Thanks for a great job in keeping MWI up-to-date!

**Comment by GwynethLlewelyn** [comment]
The issue seems to be related to the "bundles" directory. Every URL which has "bundles" in it will fail. This means that JS, CSS and images that are inside a "bundle" (like the Grid Map) will invariably throw a 404 under Nginx. So, no, this doesn't seem to be related to caching issues.

**Comment by JeffCost** [comment]
Hey GwynethLlewelyn, there was some changes in the "bundles" directory, now it should be using the "media" directory so all content uploaded to website, images etc would remain inside the media folder and it also makes a way easier to deploy using capistrano. One thing that you can check is if the media directory is 777 recursive. I will take a look in all this issues that you pointed out. Thanks

**Comment by GwynethLlewelyn** [comment]
Hmm, you're right about the "media" directory, it was 755. However, the image URLs get generated with "bundles" in it, not "media". How can I change that?

**Comment by JeffCost** [comment]
I tested last night the splash screen and gridmap module, both worked fine for me. Both modules still saving data to their respective folders inside "public/bundles". This maybe change in the future. The only problem that I had was with gridmap module. I installed a fresh install of mwi in a fresh ubuntu system. To make the map thumbnails start work I had to enable "exec" (disabled functions) in the php.ini and install imagemagick, gd and openjpeg-tools, after that I cleared the map tiles directory (/mwi/public/bundles/gridmap/img/tmp_maptiles) and all the thumbnails were generated. 

If you are doing a module update you should replace the module directory and if inside the module directory you find a directory called "public" all contents of that directory should be copied to the respective directory "public/bundles/modulename/here-goes-content-from-module-public"

**Comment by JeffCost** [comment]
Please re-open if you feel its appropriate.
