### ISSUE TITLE
Splash Screen module: no button to upload images!

### ISSUE THREAD

**Issue by GwynethLlewelyn** [Myopengrid/mwi#16]
While testing the Splash Screen module on the latest MWI version, I noticed that, while there are "browse"/"choose file"  buttons for the background images and the logo, and selecting a file works, there is strangely no way to actually upload the files. I think that the previous version had a "save" or "upload" button somewhere...

![no-upload-button-on-splash-screen-module](https://f.cloud.github.com/assets/304404/1266456/31776044-2c88-11e3-9c38-65aedfc02d55.png)

Tested with Chrome and Firefox under Mac OS X 10.7.5.

**Comment by JeffCost** [comment]
Hi GwynethLlewelyn, I tested it last night and worked fine for me. When you select the file it triggers an ajax request to upload the image, for some reason in your case the ajax is not being triggered or is failing for some reason.

**Comment by GwynethLlewelyn** [comment]
Hmmmmmmmmmmmmm. Right. The AJAX JS code is in there, but it's not being triggered. Weird, this used to work well. I wonder if there is some caching problem... I'll look into it. Thanks!

**Comment by JeffCost** [comment]
inside the module directory bundles/splashscreen you will find a directory called public. Be sure to have a copy of all its contents at public/bundles/splashscreen. (for all modules) If a module have have a public directory, the contents of that public directory should be copied to /public/bundles/MODULENAME/. I will close this issue for now, Please re-open it if you feet its appropriate.
