### ISSUE TITLE
Problems with mwi Server Error: 500 (Internal Server Error)

### ISSUE THREAD

**Issue by johnfelipe** [Myopengrid/mwi#17]
Hi please tell me about:

Server Error: 500 (Internal Server Error)

What does this mean?

Something went wrong on our servers while we were processing your request. We're really sorry about this, and will work hard to get this resolved as soon as possible.

**Comment by JeffCost** [comment]
It depends. That is a generic error message. What are you trying to do? When do you see this message? If this is a brand new installation, check the directory permissions. It should be recursive 777 for storage, media etc... check this link for a complete list of directories and files [here.](https://github.com/Myopengrid/mwi/blob/develop/README.md) 

You also could change the error details to get a better error message by changing the following:
application/config/error.php look for "detail" and change 

``` php
'detail' => false,
```

to

``` php
'detail' => true,
```

This should give you a better error message.

**Comment by johnfelipe** [comment]
i have lanmp, and a folder with virtualhost, serve that?

**Comment by johnfelipe** [comment]
I used https://github.com/lj2007331/lnmp, for apache and mysql, but i have still error

**Comment by JeffCost** [comment]
Sorry I don't know that installer script. I will close this issue for now, since I am not sure if this error message is related with MWI. Please reopen it if you have more information or you feel its appropriate.

**Comment by edwardantony** [comment]
is_writable(): open_basedir restriction in effect. File(/tmp) is not within the allowed path(s)
