### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by shadowilo** [Myopengrid/mwi#19]
Hi i am having trouble installing the module for the custom avis i can get the thumbnail to install fine but the Opensim Registration throws me an error which is as follows 

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'osregistration_activation' for key 'email_templates_slug_unique' SQL: INSERT INTO `mwi_email_templates` (`name`, `slug`, `description`, `subject`, `body`, `lang`, `type`, `module`, `is_default`, `is_core`, `updated_at`, `created_at`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) Bindings: array ( 0 => 'Grid Activation Email', 1 => 'osregistration_activation', 2 => 'The email which contains the grid activation code that is sent to a new user', 3 => '{{ settings:site_name }} - Account Activation', 4 => '
Hello {{ user:username }},

Thank you for registering at {{ settings:site_name }}. Before we can activate your account, please complete the registration process by clicking on the following link:

{{ url:base }}/osregistration/activate/{{ activation_code }}

In case your email program does not recognize the above link as, please direct your browser to the following URL:

{{ url:base }}/osregistration/activate/{{ activation_code }}

', 5 => 'en', 6 => 'html', 7 => 'osregistration', 8 => 1, 9 => 1, 10 => '2014-01-26 15:49:11', 11 => '2014-01-26 15:49:11', )

any help would be greatly appreciated 

My World My Life

**Comment by JeffCost** [comment]
In you app back end (Administration area) got to Modules -> Email -> Email Templates and delete the templates. They should be created automatically when you install the module and enable it.

**Comment by shadowilo** [comment]
it wont let me delete the templets

**Comment by JeffCost** [comment]
In this case, you need to delete the templates directly from your database. Delete the templates from the table mwi_email_templates. For some reason when the module was (installed/un-installed) the templates were not removed. I will take a look on this issue.

**Comment by JeffCost** [comment]
Closing for now. If you have more information, or the issue still persists, pelase reopen the issue.

**Comment by reserect** [comment]
I know this is a very old thread the way i dealt with this error..... Is i had to take the email mobule out from the folder completely whilst enabling the Osregistrations module then i simply placed it back into the Bundles folder afterwards and wallah both modules are now working. :).
