### ISSUE TITLE
profiles

### ISSUE THREAD

**Issue by eermsaphy** [Myopengrid/mwi#23]
This is pretty amazing stuff for us "newbies" thank you Myopengrid...
I have everything running great, everything is working but profiles and I am sure this is something on my end, but if someone could please walk me through the settings, I do see the profile module enable in the simulator so its got to be my settings in the robust file....
   I have tried the default ip...127.0.0.1
   I have tried my domain leading to it  EX mydomain.com/
    I have also moved the profiling folder from the laravel to the public tried that.. and changed the profile line to lead to it...
     ProfileServerURL = "http://127.0.0.1/miwi/profiling/[AGENT_NAME]"
It did not seem to work in the straight out of the package ran the first time without changes....

I so love this application~ just need a tad bit help

**Comment by JeffCost** [comment]
Hi Eermsaphy, The profiles module is not built in mwi yet. I will close this issue for now.
