### ISSUE TITLE
Splash page links to external website - bug or feature?

### ISSUE THREAD

**Issue by GwynethLlewelyn** [Myopengrid/mwi#5]
When testing under Imprudence:
- Flash news always bring the external browser. Isn't this supposed to be AJAXified, or is this the expected behaviour under Imprudence? (I will try to experiment with different viewers)

**Comment by Myopengrid** [comment]
Yes that is the expected behaviour. This was a personal preference when I built the page. I will be working on to add an option in the splash screen settings where you can set the flash news link as "open same page" or "open new page"

**Comment by GwynethLlewelyn** [comment]
Excellent, thank you!

**Comment by Myopengrid** [comment]
Implemented on commit da5b7b9a35219beaaaa3dcbb3bd8c320c95bf629

To apply the changes first **disable, un-install and remove** the splashscreen module. Download the application and replace the splashscreen module inside bundles directory.
