### ISSUE TITLE
Question: How to allow users to change their passwords but NOT open the grid to new registrations?

### ISSUE THREAD

**Issue by GwynethLlewelyn** [Myopengrid/mwi#6]
This is neither a bug nor a feature, but just a relatively simple question.

My grid (at opensim.betatechnologies.info) is open to the public via HyperGrid, but no new accounts are available — it's a "work grid" where only employees of my company have their accounts there. Visitors are welcome, but they have to come from the outside. So this means closing registrations on MWI. So far, so good.

But I also wish to give existing users the ability to change their passwords, because they're always forgetting them :) How is this achieved on the backoffice? I did turn new registrations off but set the ability to change passwords to active. I guess that my question is how do users get access to a page allowing them to change the password.

Is the correct place for them to go .../registration/pwreset ?

**Comment by Myopengrid** [comment]
I will have to take a look on this one since I never tested resetting the password with the registrations disabled.
Yes it should be registration/pwreset

Thank you for all your notes.

**Comment by GwynethLlewelyn** [comment]
All right, I think that I might have confused two kinds of users here. MWI users are NOT OpenSim users, right? How are the two connected?

**Comment by Myopengrid** [comment]
After you enable opensim module any user created/registered within the application will automatically be created in your grid.

**Comment by Myopengrid** [comment]
To reset password the registration module must be enabled. Go to modules -> registration -> settings and set "Registration Disabled" to yes. It should block registrations to the application but the password reset should still work.
